name = "10xdevs-project"
compatibility_date = "2023-07-10"

[build]
command = "npm run build:cloudflare"

[build.upload]
format = "modules"
dir = "dist"
main = ".cloudflare/worker.js"

[vars]
NODE_VERSION = "18"
ENABLE_VC_BUILD = "1"

[[env.production]]
name = "10xdevs-project" 